Github Actions
name: workflow 3 OCID ENV

on: 
  workflow_dispatch:
    branches:
      - DEV
    
jobs:
  to_codecommit:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-1
      REPOSITORY_NAME: you-test-codecommit-1
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with: 
          fetch-depth: 0
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }} # ここにGitHub Secretsに保存した変数名が入ります。
          aws-region: ${{ env.AWS_REGION }}
      - name: Push to CodeCommit (Mirroring)
        run: |
          git config --global credential.helper '!aws codecommit credential-helper $@'
          git config --global credential.UseHttpPath true
          git remote add codecommit https://git-codecommit.${{ env.AWS_REGION }}.amazonaws.com/v1/repos/${{ env.REPOSITORY_NAME }}
          git push --mirror codecommit

