name: Mirroring

on: 
  push:
    branches:
      - DEV
  delete:
    branches:
      - DEV
    
jobs:
  to_codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ssh://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/you-test-codecommit-2
          ssh_private_key:
            ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_2 }}
          ssh_username:
            ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_ID_2 }}
